In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv("Absenteeism_preprocessed.csv")

In [3]:
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pet,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>
                   data_preprocessed['Absenteeism Time in Hours'].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [5]:
data_preprocessed['Excessive Absenteeism'] = targets

In [6]:
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pet,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0

In [7]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [8]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                            'Distance to Work', 'Daily Work Load Average'],axis = 1)

In [9]:
data_with_targets.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet,Excessive Absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0

In [10]:
data_with_targets.shape

(700, 12)

In [11]:
data_with_targets.iloc[:,:14]

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet,Excessive Absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,5,179,40,22,1,2,0,1
696,1,0,0,0,5,225,28,24,0,1,2,0
697,1,0,0,0,5,330,28,25,1,0,0,1
698,0,0,0,1,5,235,32,25,1,0,0,0
699,0,0,0,1,5,291,40,25,0,1,1,0

In [12]:
data_with_targets.iloc[:,:-1]

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet
0,0,0,0,1,7,289,33,30,0,2,1
1,0,0,0,0,7,118,50,31,0,1,0
2,0,0,0,1,7,179,38,31,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0
4,0,0,0,1,7,289,33,30,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,5,179,40,22,1,2,0
696,1,0,0,0,5,225,28,24,0,1,2
697,1,0,0,0,5,330,28,25,1,0,0
698,0,0,0,1,5,235,32,25,1,0,0
699,0,0,0,1,5,291,40,25,0,1,1

In [13]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [16]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']
columns_to_scale = [ x for x in unscaled_inputs.columns.values if x not in columns_to_omit]
columns_to_scale

['Month Value',
 'Transportation Expense',
 'Age',
 'Body Mass Index',
 'Children',
 'Pet']

In [17]:
absenteeism_scaler = StandardScaler()

In [18]:
absenteeism_scaler.fit(unscaled_inputs[columns_to_scale])

StandardScaler()

In [19]:
unscaled_inputs[columns_to_scale] = absenteeism_scaler.fit_transform(unscaled_inputs[columns_to_scale])

In [20]:
scaled_inputs = unscaled_inputs.copy()
scaled_inputs

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet
0,0,0,0,1,0.030796,1.005844,-0.536062,0.767431,0,0.880469,0.268487
1,0,0,0,0,0.030796,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
2,0,0,0,1,0.030796,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
3,1,0,0,0,0.030796,0.854936,0.405184,-0.643782,0,0.880469,-0.589690
4,0,0,0,1,0.030796,1.005844,-0.536062,0.767431,0,0.880469,0.268487
...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,-0.568019,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
696,1,0,0,0,-0.568019,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
697,1,0,0,0,-0.568019,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
698,0,0,0,1,-0.568019,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
699,0,0,0,1,-0.568019,1.036026,0.562059,-0.408580,0,-0.019280,0.268487

In [21]:
scaled_inputs.shape

(700, 11)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
train_test_split(scaled_inputs,targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 525         1         0         0         0     0.929019
 591         0         0         0         1     0.330204
 357         0         0         1         0     1.527833
 329         0         0         0         1     1.228426
 359         0         0         1         0     0.629611
 ..        ...       ...       ...       ...          ...
 276         0         0         0         0     0.629611
 579         0         0         1         0    -1.765648
 235         0         0         0         1    -0.268611
 618         0         0         0         1    -0.568019
 647         0         0         0         1    -1.166834

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 525                2.213108 -0.849811        -0.408580          0  1.780219
 591               -0.654143 -1.006686        -1.819793          1 -0.919030
 357                1.005844 -0.536062         0.767431          0  0.880469
 329               -0.654143  0.248310         1.002633          0 -0.919030
 359               -1.574681  0.091435         0.297027          0 -0.919030
 ..                      ...       ...              ...        ...       ...
 276                0.130578  0.405184         1.943442          0  0.880469
 579               -1.016322 -0.379188        -0.408580          0  0.880469
 235                0.040034 -1.320435        -0.643782          0 -0.019280
 618               -0.654143  0.248310         1.002633          0 -0.919030
 647               -1.574681  1.503305        -0.408580          0  0.880469

           Pet
 525 -0.589690
 591 -0.589690
 357  0.268487
 329 -0.589690
 359 -0.589690
 ..        ...
 276  1.126663
 579 -0.589690
 235  1.126663
 618 -0.589690
 647 -0.589690

 [525 rows x 11 columns],
      Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 676         0         0         0         1     0.629611
 325         0         0         0         0     1.228426
 212         1         0         0         0    -0.867426
 565         1         0         0         0     1.527833
 422         0         0         0         1    -0.867426
 ..        ...       ...       ...       ...          ...
 137         0         0         0         1    -0.568019
 548         0         0         0         0     1.228426
 198         0         0         1         0    -0.867426
 289         0         0         0         1    -0.568019
 426         0         0         0         1    -1.166834

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 676                0.190942 -0.692937        -0.408580          1 -0.919030
 325                1.624567 -1.320435        -0.408580          1 -0.919030
 212                1.005844 -0.536062         0.767431          0  0.880469
 565               -0.654143 -1.006686        -1.819793          1 -0.919030
 422                0.568211 -0.065439        -0.878984          0  2.679969
 ..                      ...       ...              ...        ...       ...
 137               -0.578689 -1.477309        -1.349389          0 -0.919030
 548                1.036026  0.562059        -0.408580          0 -0.019280
 198                1.005844 -0.536062         0.767431          0  0.880469
 289                1.005844 -0.536062         0.767431          0  0.880469
 426                0.387122  1.660180         1.237836          0  0.880469

           Pet
 676 -0.589690
 325 -0.589690
 212  0.268487
 565 -0.589690
 422 -0.589690
 ..        ...
 137 -0.589690
 548  0.268487
 198  0.268487
 289  0.268487
 426  0.268487

 [175 rows x 11 columns],
 array([1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
        1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
        1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
        0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
        0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
        0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
        0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
        1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
        0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
        1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1]),
 array([0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0])]

In [24]:
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets, train_size = 0.8, random_state = 20)

In [25]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)

In [26]:
print(x_test.shape, x_test.shape)

(140, 11) (140, 11)

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [28]:
reg = LogisticRegression()

In [29]:
reg.fit(x_train, y_train)

LogisticRegression()

In [30]:
reg.score(x_train, y_train)

0.7767857142857143

In [31]:
model_outputs = reg.predict(x_train)

In [32]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True, False,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True])

In [33]:
np.sum(model_outputs == y_train)

435

In [34]:
np.sum((model_outputs == y_train))/(model_outputs.shape[0])

0.7767857142857143

In [35]:
reg.intercept_

array([-1.60957471])

In [36]:
reg.coef_

array([[ 2.77151176,  0.93168817,  3.09210221,  0.8090592 ,  0.00781237,
         0.62505482, -0.17390339,  0.28829409, -0.24081615,  0.35753531,
        -0.27337422]])

In [37]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [38]:
feature_name = unscaled_inputs.columns.values

In [39]:
summary_table = pd.DataFrame (columns = ['Feature Name'], data = feature_name)
summary_table

              Feature Name
0                 Reason_1
1                 Reason_2
2                 Reason_3
3                 Reason_4
4              Month Value
5   Transportation Expense
6                      Age
7          Body Mass Index
8                Education
9                 Children
10                     Pet

In [40]:
summary_table['Coefficient'] = np.transpose(reg.coef_)

In [41]:
summary_table

              Feature Name  Coefficient
0                 Reason_1     2.771512
1                 Reason_2     0.931688
2                 Reason_3     3.092102
3                 Reason_4     0.809059
4              Month Value     0.007812
5   Transportation Expense     0.625055
6                      Age    -0.173903
7          Body Mass Index     0.288294
8                Education    -0.240816
9                 Children     0.357535
10                     Pet    -0.273374

In [42]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

              Feature Name  Coefficient
0                Intercept    -1.609575
1                 Reason_1     2.771512
2                 Reason_2     0.931688
3                 Reason_3     3.092102
4                 Reason_4     0.809059
5              Month Value     0.007812
6   Transportation Expense     0.625055
7                      Age    -0.173903
8          Body Mass Index     0.288294
9                Education    -0.240816
10                Children     0.357535
11                     Pet    -0.273374

In [43]:
summary_table["Odd's Ratio"] = np.exp(summary_table.Coefficient)

In [44]:
summary_table

              Feature Name  Coefficient  Odd's Ratio
0                Intercept    -1.609575     0.199973
1                 Reason_1     2.771512    15.982778
2                 Reason_2     0.931688     2.538791
3                 Reason_3     3.092102    22.023327
4                 Reason_4     0.809059     2.245794
5              Month Value     0.007812     1.007843
6   Transportation Expense     0.625055     1.868348
7                      Age    -0.173903     0.840378
8          Body Mass Index     0.288294     1.334150
9                Education    -0.240816     0.785986
10                Children     0.357535     1.429801
11                     Pet    -0.273374     0.760808

In [45]:
summary_table.sort_values("Odd's Ratio",ascending = False)

              Feature Name  Coefficient  Odd's Ratio
3                 Reason_3     3.092102    22.023327
1                 Reason_1     2.771512    15.982778
2                 Reason_2     0.931688     2.538791
4                 Reason_4     0.809059     2.245794
6   Transportation Expense     0.625055     1.868348
10                Children     0.357535     1.429801
8          Body Mass Index     0.288294     1.334150
5              Month Value     0.007812     1.007843
7                      Age    -0.173903     0.840378
9                Education    -0.240816     0.785986
11                     Pet    -0.273374     0.760808
0                Intercept    -1.609575     0.199973

In [46]:
reg.score(x_test,y_test)

0.7357142857142858

In [47]:
predicted_proba = reg.predict_proba(x_test)

In [48]:
predicted_proba

array([[0.75466347, 0.24533653],
       [0.60917591, 0.39082409],
       [0.48329093, 0.51670907],
       [0.75768232, 0.24231768],
       [0.08357741, 0.91642259],
       [0.3052464 , 0.6947536 ],
       [0.303675  , 0.696325  ],
       [0.11636888, 0.88363112],
       [0.7400284 , 0.2599716 ],
       [0.75596036, 0.24403964],
       [0.50609784, 0.49390216],
       [0.19501503, 0.80498497],
       [0.06248668, 0.93751332],
       [0.7055465 , 0.2944535 ],
       [0.29675526, 0.70324474],
       [0.52028649, 0.47971351],
       [0.50551315, 0.49448685],
       [0.50843643, 0.49156357],
       [0.36713074, 0.63286926],
       [0.06422143, 0.93577857],
       [0.73822433, 0.26177567],
       [0.75768232, 0.24231768],
       [0.47994423, 0.52005577],
       [0.47760936, 0.52239064],
       [0.22619725, 0.77380275],
       [0.74047815, 0.25952185],
       [0.51148533, 0.48851467],
       [0.87702735, 0.12297265],
       [0.24005377, 0.75994623],
       [0.75768232, 0.24231768],
       [0.61140118, 0.38859882],
       [0.28761821, 0.71238179],
       [0.30178515, 0.69821485],
       [0.50492844, 0.49507156],
       [0.75768232, 0.24231768],
       [0.40227404, 0.59772596],
       [0.73957814, 0.26042186],
       [0.21977314, 0.78022686],
       [0.5601409 , 0.4398591 ],
       [0.39358874, 0.60641126],
       [0.75811152, 0.24188848],
       [0.50286997, 0.49713003],
       [0.74137615, 0.25862385],
       [0.59310285, 0.40689715],
       [0.19240806, 0.80759194],
       [0.40110655, 0.59889345],
       [0.28055298, 0.71944702],
       [0.75682238, 0.24317762],
       [0.75323874, 0.24676126],
       [0.7585402 , 0.2414598 ],
       [0.49819184, 0.50180816],
       [0.70700732, 0.29299268],
       [0.3052464 , 0.6947536 ],
       [0.75540613, 0.24459387],
       [0.17966732, 0.82033268],
       [0.60806156, 0.39193844],
       [0.09400654, 0.90599346],
       [0.73557043, 0.26442957],
       [0.67849766, 0.32150234],
       [0.6779872 , 0.3220128 ],
       [0.29497024, 0.70502976],
       [0.30376028, 0.69623972],
       [0.73420328, 0.26579672],
       [0.22415673, 0.77584327],
       [0.75458879, 0.24541121],
       [0.75509628, 0.24490372],
       [0.92448842, 0.07551158],
       [0.73912737, 0.26087263],
       [0.23823076, 0.76176924],
       [0.70359899, 0.29640101],
       [0.74227211, 0.25772789],
       [0.68460407, 0.31539593],
       [0.11591943, 0.88408057],
       [0.5612932 , 0.4387068 ],
       [0.40452581, 0.59547419],
       [0.75768232, 0.24231768],
       [0.23962732, 0.76037268],
       [0.24968437, 0.75031563],
       [0.2996782 , 0.7003218 ],
       [0.36495955, 0.63504045],
       [0.7409274 , 0.2590726 ],
       [0.92558608, 0.07441392],
       [0.73145547, 0.26854453],
       [0.28379938, 0.71620062],
       [0.53265409, 0.46734591],
       [0.87778217, 0.12221783],
       [0.30326582, 0.69673418],
       [0.47760936, 0.52239064],
       [0.77739845, 0.22260155],
       [0.28761821, 0.71238179],
       [0.80291504, 0.19708496],
       [0.86732465, 0.13267535],
       [0.75379629, 0.24620371],
       [0.75423014, 0.24576986],
       [0.75596036, 0.24403964],
       [0.12930173, 0.87069827],
       [0.75379629, 0.24620371],
       [0.27679152, 0.72320848],
       [0.75497368, 0.24502632],
       [0.80068474, 0.19931526],
       [0.40339941, 0.59660059],
       [0.28761821, 0.71238179],
       [0.30213847, 0.69786153],
       [0.29254388, 0.70745612],
       [0.56071713, 0.43928287],
       [0.56474607, 0.43525393],
       [0.75466347, 0.24533653],
       [0.12930173, 0.87069827],
       [0.23738775, 0.76261225],
       [0.86759359, 0.13240641],
       [0.92590765, 0.07409235],
       [0.08788486, 0.91211514],
       [0.35675261, 0.64324739],
       [0.6130671 , 0.3869329 ],
       [0.40396248, 0.59603752],
       [0.39582409, 0.60417591],
       [0.21937231, 0.78062769],
       [0.15389863, 0.84610137],
       [0.43937218, 0.56062782],
       [0.7386761 , 0.2613239 ],
       [0.75552858, 0.24447142],
       [0.8760147 , 0.1239853 ],
       [0.19538249, 0.80461751],
       [0.50462418, 0.49537582],
       [0.75596036, 0.24403964],
       [0.70457368, 0.29542632],
       [0.75811152, 0.24188848],
       [0.8667854 , 0.1332146 ],
       [0.30277181, 0.69722819],
       [0.73822433, 0.26177567],
       [0.3930306 , 0.6069694 ],
       [0.75811152, 0.24188848],
       [0.75682238, 0.24317762],
       [0.70115414, 0.29884586],
       [0.73374656, 0.26625344],
       [0.40847604, 0.59152396],
       [0.50492844, 0.49507156],
       [0.70311094, 0.29688906],
       [0.75497368, 0.24502632],
       [0.55956451, 0.44043549]])

In [49]:
predicted_proba.shape

(140, 2)

In [55]:
predicted_proba[:,1]

array([0.24533653, 0.39082409, 0.51670907, 0.24231768, 0.91642259,
       0.6947536 , 0.696325  , 0.88363112, 0.2599716 , 0.24403964,
       0.49390216, 0.80498497, 0.93751332, 0.2944535 , 0.70324474,
       0.47971351, 0.49448685, 0.49156357, 0.63286926, 0.93577857,
       0.26177567, 0.24231768, 0.52005577, 0.52239064, 0.77380275,
       0.25952185, 0.48851467, 0.12297265, 0.75994623, 0.24231768,
       0.38859882, 0.71238179, 0.69821485, 0.49507156, 0.24231768,
       0.59772596, 0.26042186, 0.78022686, 0.4398591 , 0.60641126,
       0.24188848, 0.49713003, 0.25862385, 0.40689715, 0.80759194,
       0.59889345, 0.71944702, 0.24317762, 0.24676126, 0.2414598 ,
       0.50180816, 0.29299268, 0.6947536 , 0.24459387, 0.82033268,
       0.39193844, 0.90599346, 0.26442957, 0.32150234, 0.3220128 ,
       0.70502976, 0.69623972, 0.26579672, 0.77584327, 0.24541121,
       0.24490372, 0.07551158, 0.26087263, 0.76176924, 0.29640101,
       0.25772789, 0.31539593, 0.88408057, 0.4387068 , 0.59547419,
       0.24231768, 0.76037268, 0.75031563, 0.7003218 , 0.63504045,
       0.2590726 , 0.07441392, 0.26854453, 0.71620062, 0.46734591,
       0.12221783, 0.69673418, 0.52239064, 0.22260155, 0.71238179,
       0.19708496, 0.13267535, 0.24620371, 0.24576986, 0.24403964,
       0.87069827, 0.24620371, 0.72320848, 0.24502632, 0.19931526,
       0.59660059, 0.71238179, 0.69786153, 0.70745612, 0.43928287,
       0.43525393, 0.24533653, 0.87069827, 0.76261225, 0.13240641,
       0.07409235, 0.91211514, 0.64324739, 0.3869329 , 0.59603752,
       0.60417591, 0.78062769, 0.84610137, 0.56062782, 0.2613239 ,
       0.24447142, 0.1239853 , 0.80461751, 0.49537582, 0.24403964,
       0.29542632, 0.24188848, 0.1332146 , 0.69722819, 0.26177567,
       0.6069694 , 0.24188848, 0.24317762, 0.29884586, 0.26625344,
       0.59152396, 0.49507156, 0.29688906, 0.24502632, 0.44043549])

In [56]:
import pickle

In [57]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [58]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)